services:
  proxy:
    image: ghcr.io/themansabmir/proxy:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - WHATSAPP_VERIFY_TOKEN=wLw78iGAuMWk1sZ6kIPTZkpcBxCt
      - PORT=4001
    volumes:
      - ./data:/app/data
